"options":
  "extra_packages":
    "description": "Space separated list of extra deb packages to install.\n"
    "type": "string"
    "default": ""
  "package_status":
    "default": "install"
    "type": "string"
    "description": |
      the status of service-affecting packages will be set to this
      value in the dpkg database. valid values are "install" and "hold".
  "install_sources":
    "description": |
      list of extra apt sources, per charm-helpers standard
      format (a yaml list of strings encoded as a string). each source
      may be either a line that can be added directly to
      sources.list(5), or in the form ppa:<user>/<ppa-name> for adding
      personal package archives, or a distribution component to enable.
    "type": "string"
    "default": |
      -  "deb https://oss-binaries.phusionpassenger.com/apt/passenger xenial main"
  "install_keys":
    "description": |
      list of signing keys for install_sources package sources, per
      charmhelpers standard format (a yaml list of strings encoded as
      a string). the keys should be the full ascii armoured gpg public
      keys. while gpg key ids are also supported and looked up on a
      keyserver, operators should be aware that this mechanism is
      insecure. null can be used if a standard package signing key is
      used that will already be installed on the machine, and for ppa
      sources where the package signing key is securely retrieved from
      launchpad.
    "type": "string"
    "default": |
      - 561F9B9CAC40B2F7
  "port":
    "type": "int"
    "default": !!int "80"
    "description": |
      NGINX listen port
  "host":
    "type": "string"
    "default": "127.0.0.1"
    "description": "listen address"
  "api-dir":
    "type": "string"
    "default": "/opt/tengu_ui"
    "description": |
      The location where the ui will be installed
  "user":
    "type": "string"
    "default": "tengu"
    "description": |
      The linux user that will be created to run the api
  "nginx-group":
    "type": "string"
    "default": "www-data"
    "description": |
      The linux group of which nginx is a member
  "setup":
    "type": "string"
    "default": "letsencrypt"
    "description": |
      Choose the type of install: https [client] with client certificates, https [letsencrypt] with
      letsencrypt certificates. If an option is entered which does not match [client, letsencrypt], defaults to letsencrypt.
      the setup and config for letsencrypt is a manual process, which is documented in the readme.
  "fullchain":
    "type": "string"
    "default": ""
    "description": |
      Specify the location of the ssl fullchain. Leave blank if you want the charm to setup a letsencrypt certificate
  "privatekey":
    "type": "string"
    "default": ""
    "description": |
      Specify the location of the ssl privatekey. Leave blank if you want the charm to setup a letsencrypt certificate
  "dhparam":
    "type": "string"
    "default": "/etc/nginx/ssl/dhparam.pem"
    "description": |
      Location of the DH.pem file
  "bundles_url":
    "type": "string"
    "default": "http://tengu.io/bundles/{{bundlename}}.json"
    "description": |
      Specify the location of custom bundles
  "mappings_url":
    "type": "string"
    "default": ""
    "description": |
      Specify the location of needed mappings between applications
