"options":
  "extra_packages":
    "description": "Space separated list of extra deb packages to install.\n"
    "type": "string"
    "default": ""
  "package_status":
    "default": "install"
    "type": "string"
    "description": "The status of service-affecting packages will be set to this value\
      \ in the dpkg database. Valid values are \"install\" and \"hold\".\n"
  "install_sources":
    "description": |
      list of extra apt sources, per charm-helpers standard
      format (a yaml list of strings encoded as a string). each source
      may be either a line that can be added directly to
      sources.list(5), or in the form ppa:<user>/<ppa-name> for adding
      personal package archives, or a distribution component to enable.
    "type": "string"
    "default": |
      - 'deb https://artifacts.elastic.co/packages/5.x/apt stable main'
  "install_keys":
    "description": |
      list of signing keys for install_sources package sources, per
      charmhelpers standard format (a yaml list of strings encoded as
      a string). the keys should be the full ascii armoured gpg public
      keys. while gpg key ids are also supported and looked up on a
      keyserver, operators should be aware that this mechanism is
      insecure. null can be used if a standard package signing key is
      used that will already be installed on the machine, and for ppa
      sources where the package signing key is securely retrieved from
      launchpad.
    "type": "string"
    "default": |
      - |
          -----BEGIN PGP PUBLIC KEY BLOCK-----
          Version: GnuPG v2.0.14 (GNU/Linux)

          mQENBFI3HsoBCADXDtbNJnxbPqB1vDNtCsqhe49vFYsZN9IOZsZXgp7aHjh6CJBD
          A+bGFOwyhbd7at35jQjWAw1O3cfYsKAmFy+Ar3LHCMkV3oZspJACTIgCrwnkic/9
          CUliQe324qvObU2QRtP4Fl0zWcfb/S8UYzWXWIFuJqMvE9MaRY1bwUBvzoqavLGZ
          j3SF1SPO+TB5QrHkrQHBsmX+Jda6d4Ylt8/t6CvMwgQNlrlzIO9WT+YN6zS+sqHd
          1YK/aY5qhoLNhp9G/HxhcSVCkLq8SStj1ZZ1S9juBPoXV1ZWNbxFNGwOh/NYGldD
          2kmBf3YgCqeLzHahsAEpvAm8TBa7Q9W21C8vABEBAAG0RUVsYXN0aWNzZWFyY2gg
          KEVsYXN0aWNzZWFyY2ggU2lnbmluZyBLZXkpIDxkZXZfb3BzQGVsYXN0aWNzZWFy
          Y2gub3JnPokBOAQTAQIAIgUCUjceygIbAwYLCQgHAwIGFQgCCQoLBBYCAwECHgEC
          F4AACgkQ0n1mbNiOQrRzjAgAlTUQ1mgo3nK6BGXbj4XAJvuZDG0HILiUt+pPnz75
          nsf0NWhqR4yGFlmpuctgCmTD+HzYtV9fp9qW/bwVuJCNtKXk3sdzYABY+Yl0Cez/
          7C2GuGCOlbn0luCNT9BxJnh4mC9h/cKI3y5jvZ7wavwe41teqG14V+EoFSn3NPKm
          TxcDTFrV7SmVPxCBcQze00cJhprKxkuZMPPVqpBS+JfDQtzUQD/LSFfhHj9eD+Xe
          8d7sw+XvxB2aN4gnTlRzjL1nTRp0h2/IOGkqYfIG9rWmSLNlxhB2t+c0RsjdGM4/
          eRlPWylFbVMc5pmDpItrkWSnzBfkmXL3vO2X3WvwmSFiQbkBDQRSNx7KAQgA5JUl
          zcMW5/cuyZR8alSacKqhSbvoSqqbzHKcUQZmlzNMKGTABFG1yRx9r+wa/fvqP6OT
          RzRDvVS/cycws8YX7Ddum7x8uI95b9ye1/Xy5noPEm8cD+hplnpU+PBQZJ5XJ2I+
          1l9Nixx47wPGXeClLqcdn0ayd+v+Rwf3/XUJrvccG2YZUiQ4jWZkoxsA07xx7Bj+
          Lt8/FKG7sHRFvePFU0ZS6JFx9GJqjSBbHRRkam+4emW3uWgVfZxuwcUCn1ayNgRt
          KiFv9jQrg2TIWEvzYx9tywTCxc+FFMWAlbCzi+m4WD+QUWWfDQ009U/WM0ks0Kww
          EwSk/UDuToxGnKU2dQARAQABiQEfBBgBAgAJBQJSNx7KAhsMAAoJENJ9ZmzYjkK0
          c3MIAIE9hAR20mqJWLcsxLtrRs6uNF1VrpB+4n/55QU7oxA1iVBO6IFu4qgsF12J
          TavnJ5MLaETlggXY+zDef9syTPXoQctpzcaNVDmedwo1SiL03uMoblOvWpMR/Y0j
          6rm7IgrMWUDXDPvoPGjMl2q1iTeyHkMZEyUJ8SKsaHh4jV9wp9KmC8C+9CwMukL7
          vM5w8cgvJoAwsp3Fn59AxWthN3XJYcnMfStkIuWgR7U2r+a210W6vnUxU4oN0PmM
          cursYPyeV0NX/KQeUeNMwGTFB6QHS/anRaGQewijkrYYoTNtfllxIu9XYmiBERQ/
          qPDlGRlOgVTd9xUfHFkzB52c70E=
          =92oX
          -----END PGP PUBLIC KEY BLOCK-----
  "install-type":
    "type": "string"
    "default": "full"
    "description": |
      Override of the install-type. NOT TO BE ADJUSTED.
  "java-major":
    "type": "string"
    "default": "8"
    "description": "Override of the java-major. NOT TO BE ADJUSTED.  \n"
  "java-flavor":
    "type": "string"
    "default": "openjdk"
    "description": |
      Override of the java-flavor. NOT TO BE ADJUSTED.
  "firewall_enabled":
    "description": |
      this option will enable or disable the ufw. By default this is set to
      'false' since the firewall is never enabled when a machine or container
      is created with juju. Set to 'true' to enable firewall. Once enabled
      rules will be added when another charm has a relation with elasticsearch.
      This charm will be able to access elasticsearch on port 9200, while
      all the other traffice to that port will be blocked. Enabling the firewall
      will also allow port 22 from anywhere.
    "type": "boolean"
    "default": !!bool "true"
  "cluster_name":
    "description": |
      This sets the elasticsearch cluster name. This name is then added to the
      elasticsearch.yml file
    "type": "string"
    "default": "elasticsearch"
  "api-key":
    "type": "string"
    "default": "ce379ddaa7f7008cd0c6fc86d38ad378bb2b5ac6e6e335b844354e8bfa56f686"
    "description": |
      the API key that is needed to send a request to the sojobo
  "sojobo-ip":
    "type": "string"
    "default": "10.132.30.102"
    "description": |
      IP or url of the sojobo-api
  "username":
    "type": "string"
    "default": "sojobo"
    "description": |
      The username used to get access to nginx. This username will be used by the
      sojobo to get information out of elasticsearch.
  "pass":
    "type": "string"
    "default": "mighty molten volunteers"
    "description": |
      Encrypted password used for basic auth configuration of nginx.
  "port":
    "type": "string"
    "default": "80"
    "description": |
      port used where the webserver will be available. This is default set to 80.
  "controller-type":
    "type": "string"
    "default": "aws"
    "description": |
      type of controller where this charm will be deployed. Possible options are
      aws, google or MAAS, This value will be generated when model will be
      created. DO NOT CHANCE THIS!
  "controller":
    "type": "string"
    "default": "aws"
    "description": |
      Name of the controller where this charm will be deployed. This value will
      be generated when model will be created. DO NOT CHANCE THIS!
  "model":
    "type": "string"
    "default": "demo"
    "description": |
      Name of the model where this charm will be deployed. This value will
      be generated when model will be created. DO NOT CHANCE THIS!
