"options":
  "partitions":
    "type": "int"
    "default": !!int "1"
    "description": |
      The number of partitions for the topic being created or altered. WARNING!
      If partitions are increased for a topic that has a key, the partition
      logic or ordering of the messages will be affected
  "replication-factor":
    "type": "int"
    "default": !!int "1"
    "description": |
      The replication factor for each partition in the topic being created.
