"options":
  "extra_packages":
    "description": "Space separated list of extra deb packages to install.\n"
    "type": "string"
    "default": ""
  "package_status":
    "default": "install"
    "type": "string"
    "description": "The status of service-affecting packages will be set to this value\
      \ in the dpkg database. Valid values are \"install\" and \"hold\".\n"
  "install_sources":
    "description": "List of extra apt sources, per charm-helpers standard format (a\
      \ yaml list of strings encoded as a string). Each source may be either a line\
      \ that can be added directly to sources.list(5), or in the form ppa:<user>/<ppa-name>\
      \ for adding Personal Package Archives, or a distribution component to enable.\n"
    "type": "string"
    "default": ""
  "install_keys":
    "description": "List of signing keys for install_sources package sources, per\
      \ charmhelpers standard format (a yaml list of strings encoded as a string).\
      \ The keys should be the full ASCII armoured GPG public keys. While GPG key\
      \ ids are also supported and looked up on a keyserver, operators should be aware\
      \ that this mechanism is insecure. null can be used if a standard package signing\
      \ key is used that will already be installed on the machine, and for PPA sources\
      \ where the package signing key is securely retrieved from Launchpad.\n"
    "type": "string"
    "default": ""
  "monitoring-url":
    "type": "string"
    "default": "http://104.197.215.6/monitoring/ping"
    "description": "URL where to send the ping to."
  "monitoring-api-key":
    "type": "string"
    "default": "bea527118ca7110a9f08a5087a172981db809b238437a15b09e49a725bb3238e"
    "description": "API-key for the monitoring api"
  "controller":
    "type": "string"
    "default": ""
    "description": "Name of the controller on which proxy is deployed"
  "model":
    "type": "string"
    "default": ""
    "description": "Name of the model on which proxy is deployed"
  "credentials":
    "type": "string"
    "default": "test test"
    "description": "Space-separated username and password for basic authentication"
