"options":
  "ssl_key":
    "type": "string"
    "default": "abc"
    "description": |
      private unencrypted key in base64 PEM format (starts "-----BEGIN RSA PRIVATE KEY-----")
  "ssl_cert":
    "type": "string"
    "default": "def"
    "description": |
      X.509 certificate in base64 PEM format (starts "-----BEGIN CERTIFICATE-----")
  "rabbitmq":
    "type": "string"
    "default": "<ip>:<port>"
    "description": |
      URL and port on which the exposed RabbitMQ is available
  "password":
    "type": "string"
    "default": ""
    "description": |
      Password for the sensu user for the /sensu vhost on RabbitMQ
