"options":
  "monitoring-url":
    "type": "string"
    "default": "http://104.197.215.6/monitoring/ping"
    "description": "URL where to send the ping to."
  "monitoring-api-key":
    "type": "string"
    "default": "bea527118ca7110a9f08a5087a172981db809b238437a15b09e49a725bb3238e"
    "description": "API-key for the monitoring api"
  "controller":
    "type": "string"
    "default": ""
    "description": "Name of the controller on which proxy is deployed"
  "model":
    "type": "string"
    "default": ""
    "description": "Name of the model on which proxy is deployed"
  "controller-type":
    "type": "string"
    "default": ""
    "description": "Controller-type"
  "credentials":
    "type": "string"
    "default": "test test"
    "description": "Space-separated username and password for basic authentication"
  "fqdn":
    "type": "string"
    "default": ""
    "description": "URL on which the Nginx-proxy is accessable over https"
